branches:
    only:
        - master
language: python
python:
    - "2.7"
services:
    - docker
matrix:
    include:
        - language: python
          python: 3.6
          cache: pip
          script:
            - scripts/travis-docs
        - language: python
          python: 2.7
          env:
            UID=0
            DOCKER_COMPOSE_VERSION=1.23.2
          cache:
            directories:
              - downloads
              - build
              - static
          script:
            - set -e
            - scripts/travis-python
            - scripts/travis-localerefresh
          after_success:
            - bash <(curl -s https://codecov.io/bash)
        - language: node_js
          node_js: 10
          cache: npm
          script:
            - scripts/travis-js
